# Generated by Django 5.1.4 on 2024-12-13 01:24

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
